// import localFont from "next/font/local";
// import "./globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import "./globals.css"
// import { Inter } from "next/font/google"
// import Link from "next/link"

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Helmet Detection App",
//   description: "AI-powered helmet detection for workplace safety",
// }

// export default function RootLayout({
//   children,
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <nav className="bg-purple-900 text-white p-4">
//           <div className="container mx-auto flex justify-between items-center">
//             <Link href="/" className="text-xl font-bold">
//               Helmet Detection
//             </Link>
//             <div className="space-x-4">
//               <Link href="/" className="hover:text-purple-200">
//                 Home
//               </Link>
//               <Link href="/dashboard" className="hover:text-purple-200">
//                 Dashboard
//               </Link>
//             </div>
//           </div>
//         </nav>
//         {children}
//       </body>
//     </html>
//   )
// }
import "./globals.css"
import Link from "next/link"

export const metadata = {
  title: "Helmet Detection App",
  description: "AI-powered helmet detection for workplace safety",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="bg-purple-900 text-white p-4">
          <div className="container mx-auto flex justify-between items-center">
            <Link href="/" className="text-xl font-bold">
              Helmet Detection
            </Link>
            <div className="space-x-4">
              <Link href="/" className="hover:text-purple-200">
                Home
              </Link>
              <Link href="/dashboard" className="hover:text-purple-200">
                Dashboard
              </Link>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  )
}
